GET https://localhost/tiririt/api/v1/WatchList
x-requested-with: XMLHttpRequest
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IlNTdzVkM1hOeWMwMjJsejVoaHlKUFEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1OTI2OTA1MzIsImV4cCI6MTU5MjY5NDEzMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvdGlyaXJpdCIsImF1ZCI6IklkZW50aXR5U2VydmVyQXBpIiwiY2xpZW50X2lkIjoidGlyaXJpdCIsInN1YiI6IjMiLCJhdXRoX3RpbWUiOjE1OTI2OTA1MzIsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiSWRlbnRpdHlTZXJ2ZXJBcGkiXSwiYW1yIjpbInB3ZCJdfQ.qwyi14kuIT_fNLlhv3jv_KmbhamMLBHgv2Bo5jwqoRVAt6i-5lj4vz21Mj3pVT8Fa554g5J_kh0IF80dJpusSCoZ44F0C89HIyUoXzaPDkxgcKyaaop6h18ObyhSESdluGwdq2dOy0bwaiQy7dh9wALFzptpSSSEZQKqeoXUW1OmDrcZdwjbBdayfh-JBytc7vVBFNve_oziPHwH35Nu2SVp415OVZMJR2ur0r2i1Sthyq_doEEtvZIUdScCNe-EfeElhnBZcHp5W2yDwbOtFresh0buML7hgw49Ts_pcETrG6h86Lr4Gwn4XJI9YPNdnnaUjrKzmKtec71bGGf8AQ

###

GET https://investing.einnews.com/rss/dh5LoBFONe1cJ1s0

###
GET http://localhost:49242/Home/Secret
    Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzb21lX2lkIiwiR3Jhbm55IjoiY29va2llIiwibmJmIjoxNTkxNDA5NzkyLCJleHAiOjE1OTE0OTYxOTIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDkyNDIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQ5MjQyIn0.A3rvuu60PQXCVtPjAqhYqGHdJZqsbT0TpmDgp9W6Up8"

###
GET http://localhost/tiriritapi/connect/authorize?client_id=Tirir2it&scope=openid&response_type=id_token&redirect_uri=http://localhost:4200/authentication/login-callback&state=abc&nonce=xyz

###
GET /common/v2.0/.well-known/openid-configuration
Host: login.microsoftonline.com