GET https://localhost:44303/api/v1/WathcList

###

GET https://investing.einnews.com/rss/dh5LoBFONe1cJ1s0

###
GET https://localhost:44308/Home/Secret
Content-Type: application/json

{
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzb21lX2lkIiwiR3Jhbm55IjoiY29va2llIiwibmJmIjoxNTkxNDA5NzkyLCJleHAiOjE1OTE0OTYxOTIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDkyNDIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQ5MjQyIn0.A3rvuu60PQXCVtPjAqhYqGHdJZqsbT0TpmDgp9W6Up8"
}
